### ISSUE TITLE
Warn/error on mixing tabs and spaces

### ISSUE THREAD

**Issue by Kha** [leanprover/lean4#339]
Doing so can create nigh-undebuggable errors in indentation-sensitive code.
Simplest solution: ban tabs outright

**Comment by leodemoura** [comment]
@Kha What other whitespace-sensitive languages do in this kind of situation?

**Comment by Kha** [comment]
GHC seems to interpret them as 8 spaces, but started warning about them by default at some point https://downloads.haskell.org/ghc/latest/docs/html/users_guide/using-warnings.html#ghc-flag--Wtabs
Python 3 rejects code where the meaning is dependent on the size of a tab https://stackoverflow.com/questions/2034517/pythons-interpretation-of-tabs-and-spaces-to-indent
Elm doesn't seem to allow tabs at all https://www.reddit.com/r/elm/comments/5476yt/no_tabs_seriously/ :grin:
So I stand by my recommendation :)

**Comment by leodemoura** [comment]
Moved it to high priority because we must apply this change before first official release.

**Comment by tydeu** [comment]
Couldn't this be resolved by having an Nat option `tabSize`  that sets the width (in spaces) of a tab and then the parser just expands hard tabs into that number of spaces?

**Comment by Kha** [comment]
No, that does not resolve the issue that mixing tabs and spaces would show differently indented code to users with different tab settings.

**Comment by tydeu** [comment]
> No, that does not resolve the issue that mixing tabs and spaces would show differently indented code to users with different tab settings.

What? I imagine that is why they have different tab settings, because they want it to appear different? This also seems more like a end-user concern than language though. If I have `set_option tabSize 2` and then set my editor to tab size 4, that would seem to be more of a me problem.

Furthermore, most editors (such as VS code) allow you to configure tab size on a per-project basis (and that configuration can be committed along with the project) so as long as the project is configured with the same tab size as Lean, it would appear the same to all users of the project? So there shouldn't necessarily be any problem with cross-user editor configurations.

I think banning tabs is extremely drastic, highly opinionated solution for something that really doesn't need it. Many developers like hard tabs, closing Lean off to them seems unnecessary.

**Comment by sertonix** [comment]
Does one seriously need to preprocess lean files with `tr '\t' ' '` to use tabs?

**Comment by nomeata** [comment]
You don't have to do it seriously, but otherwise, yes.
