### ISSUE TITLE
simp_all? omits unfolded let hypotheses

### ISSUE THREAD

**Issue by JLimperg** [leanprover/lean4#3519]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Check that your issue is not already [filed](https://github.com/leanprover/lean4/issues).
    * Reduce the issue to a minimal, self-contained, reproducible test case. Avoid dependencies to mathlib4 or std4.

### Description

`simp_all?` does not mention unfolded `let` hypotheses in the generated `simp_all only` call:

```lean
example {P : Nat → Prop} : let x := 0; P x := by
  intro x
  simp_all? [x] -- Try this: simp_all only

example {P : Nat → Prop} : let x := 0; P x := by
  intro x
  simp_all only -- simp_all made no progress
```

The buggy code is [here](https://github.com/leanprover/lean4/blob/2e4557dbd0a0641a8ab6f9c660f9c96504b785b4/src/Lean/Elab/Tactic/Simp.lean#L361).

### Context

Similar to #3501.

### Versions

nightly 2024-02-27

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by leodemoura** [comment]
Fixed by commit above. It has been squashed.

**Comment by m4lvin** [comment]
See https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/simp_all.3F.20.E2.89.A0.20simp_all.20and.20an.20old.20bug.3F/near/476414205

This bug seems to be back, so this should be reopened?

**Comment by nomeata** [comment]
> Note: the test case added by the above commit uses simp and not simp_all. Could that be why the bug is not caught by the CI tests?

Ah, I was just thoroughly confused by that as well. Yes, then the bug is not fully fixed, I’ll reopen.
