### ISSUE TITLE
Can error message be improved in this case?

### ISSUE THREAD

**Issue by lovettchris** [leanprover/lean4#765]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

```
def double :=
  fun (x : Nat) => x + x

#eval double
```

fails to synthesize...

### Steps to Reproduce
See above

**Expected behavior:** [What you expect to happen]

"Cannot evaluate function 'double' because you are missing an argument'

**Actual behavior:** [What actually happens]

```
failed to synthesize
  Lean.MetaEval (Nat → Nat)
```

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `lean --version`,
please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by lovettchris** [comment]
Daniel showed me that you can write that kind of error message yourself in user space
```lean
universe u v
variable {α : Type u} {β : Type v}

instance : Lean.Eval (α → β) :=
  ⟨fun _ _ => throw (IO.userError "cannot evaluate a function -- did you forget arguments?")⟩

def double := fun (x : Nat) => x + x

#eval double -- error: cannot evaluate a function -- did you forget arguments?
```
Seems a useful thing to ship out of the box, no?

**Comment by tydeu** [comment]
@lovettchris the problem is that for some functions, it can be perfectly reason to have a proper `Eval` instance for them that does evaluate. For example, lazy `Unit -> a` functions or various function-based monads (`StateT`, `ReaderT`, etc.).

**Comment by leodemoura** [comment]
@tydeu I agree that we want to be able to evaluate some functions, the `Unit -> a` is a great example. That being said, I also agree the current error message sucks.
I see two possible solutions: 

1- We modify the current `#eval` elaborator, and try to produce a nicer error message when we fail to synthesize the instance.

2- We add the instance above, and mark it as a low priority one.

**Comment by tydeu** [comment]
@leodemoura To elaborate on my +1, I think to extent, both can be useful. 

(1) is helpful for things beyond functions to give new users a bit more insight into what is going on. One thing in particular, would be to inform users that either an `Eval` *or* `MetaEval` instance is needed. 

(2) has the benefit of a more tailored error message in the case of functions. However, if phrased improperly, it has the danger of potentially misleading users into thinking it is impossible for functions to be eval'ed.

**Comment by leodemoura** [comment]
@tydeu I agree with your remarks.
I implemented 1) above. I will push it soon. Here is the new error message.
```
error: expression
  double
has type
  Nat → Nat
but instance
  Lean.Eval (Nat → Nat)
failed to be synthesized, this instance instructs Lean on how to display the resulting value, recall that any type implementing the `Repr` class also implements the `Lean.Eval` class
``` 
We can now easily tweak the message and clarify it if needed.

**Comment by lovettchris** [comment]
Better but still not as good as "Missing argument `x` for function `double`."

**Comment by tydeu** [comment]
@leodemoura cool, looks much better to me! 

My comment on the message itself is that it is quite long for an error message, and it seems too heavily focus on displaying values, when `#eval` is much more general than that (e.g., it also often used with `IO` monads and the like). I would go with something more concise:

```
error:
  double
has type
  Nat → Nat
but Lean failed to synthesize the instance
  Lean.Eval (Nat → Nat)
that informs Lean how to evaluate the expression
```

@lovettchris if that is the user's problem (which it may not be), I think one could gather that from the fact `double` has type `Nat -> Nat` rather than the likely desired type `Nat`.

**Comment by leodemoura** [comment]
> Better but still not as good as "Missing argument `x` for function `double`."

The `Lean.Eval <type>` synthesis may fail for many different reasons. The error message above is "guessing" a common failure for functions, but it is not the only one.  Consider the following example
```lean
instance (priority := low) {α : Type u} {β : Type v} : Lean.Eval (α → β) :=
  ⟨fun _ _ => throw (IO.userError "cannot evaluate a function -- did you forget arguments?")⟩

def double (x : Nat) := 2*x

#eval double -- Error: cannot evaluate a function -- did you forget arguments?

instance {α : Type u} [Repr α] : Repr (Unit → α) :=
  ⟨fun v _ => "fun _ => " ++ repr (v ())⟩

#eval fun _ : Unit => 10 + 20 -- fun _ => 30

inductive Foo where
  | a | b | c

#eval fun _ : Unit => Foo.a -- Error: cannot evaluate a function -- did you forget arguments?
```
The error message for the last example is bad. It fails because we don't have `Repr Foo` nor `Lean.Eval Foo`.

**Comment by leodemoura** [comment]
@tydeu Yeah, the new error message is long, but I want to provide the most common "fix": define the `Repr` instance for the resulting type.

**Comment by tydeu** [comment]
@leodemoura in that case, how about something like:
```
error:
  double
has type
  Nat → Nat
but Lean failed to synthesize the instance
  Repr (Nat → Nat)
or
  Lean.Eval (Nat → Nat)
or (with `import Lean`) 
  Lean.MetaEval (Nat → Nat)
that inform Lean how to evaluate the expression
```

**Comment by leodemoura** [comment]
@tydeu Not sure. There is only one failure: Lean failed to synthesize `Lean.Eval (Nat -> Nat)`. In the error message, I just tried to remind the user that we have the instance
```lean
instance [Repr α] : Eval α where
  eval a _ := IO.println (repr (a ()))
```
and in most cases, adding the `Repr` instance is how we fix the problem.

**Comment by tydeu** [comment]
@leodemoura yeah, my statement that it failed to synthesize each of those options is not exactly true, However, for `Repr` at least, since there is that instance, a failure to synthesize` Eval a` does technically imply a failure to evaluate `Repr a`. 

My goal with second version of the error message edit is to not that evaluation can be beyond simply `Repr` displays while still giving a hint towards that common problem. I also wanted to address the common reason I see this error when testing simple meta code is that I forget that to use `MetaEval`  one needs to `import Lean`,
