### ISSUE TITLE
TC synthesis fails with `unknown metavariable`

### ISSUE THREAD

**Issue by lecopivo** [leanprover/lean4#971]
I'm getting an error `unknown metavariable '?_uniq.6088'` during type class synthesis. From my limited understanding this is almost always a bug. Unfortunately, I was unable to create self contained mwe, and the only way I can reproduce it is by cloning my ​repository.

```
git clone --branch tc_problem https://github.com/lecopivo/SciLean.git
cd SciLean
lake build
```

The error should be:
```
./SciLean/Data/Table.lean:124:2: error: unknown metavariable '?_uniq.6088'
```

It is likely the type class instances are incorrectly set up and TC gets into an infinite loop, but still the error message  `unknown metavariable '?_uniq.6088'` is highly suspicious.

Please do not bother trying to figure out the tangle of typeclasses. I have two classes in which I did not find `outParam` sufficient to achieve what I need do, so I devised a `Trait` [class trick](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Typeclass.20timeout.20and.20outParam/near/265502136). This error is a result of some non-trivial interaction of Trait classes for SemiInner and Table.

**Comment by leodemoura** [comment]
Yes, `unknown metavariable` is usually due to a bug in Lean or a user metaprogram. 
We currently do not have cycles to investigate issues that are reported without a self-contained mwe. We would be very grateful if you create one. The standard recipe is to keep incrementally removing dependencies.

**Comment by lecopivo** [comment]
Understandable, will keep poking at it and hopefully reduce it to something smaller.

**Comment by lecopivo** [comment]
I have managed to produce mwe:

```
class Vec (X : Type u) 

class IsLin {X Y} [Vec X] [Vec Y] (f : X → Y)

def ℝ := Float

instance : Vec ℝ := sorry
instance {α : Type u} {X : Type v} [Vec X] : Vec (α → X) := sorry
instance {X : Type u} {Y : Type v} [Vec X] [Vec Y] : Vec (X × Y) := sorry

--------------

instance swap_is_lin {α : Type} {Y Z : Type} [Vec Y] [Vec Z] 
  (f : α → Y → Z) [∀ a, IsLin (f a)] 
  : IsLin (λ y a => f a y) := sorry
instance comp_is_lin {X Y Z : Type} [Vec X] [Vec Y] [Vec Z] 
  (f : Y → Z) (g : X → Y) [IsLin f] [IsLin g] 
  : IsLin (λ x => f (g x)) := sorry

----------------

class Trait (X : Type u) where
  R : Type v
  D : Type w
  eval : R → D → ℝ

attribute [reducible] Trait.R Trait.D Trait.eval

class SemiInner (X : Type u) (R : Type v) (D : Type w) (eval : R → D → ℝ) where  
  semiInner : X → X → R
  testFunction : D → X → Prop

@[reducible] instance (X) (R : Type u) (D : Type v) (e : R → D → ℝ) [SemiInner X R D e] : Trait X := ⟨R, D, e⟩

class SemiHilbert (X) (R : Type u) (D : Type v) (e : R → D → ℝ) [outParam $ Vec R] extends Vec X, SemiInner X R D e 

instance (X R D e) [Trait X] [Vec R] [SemiHilbert X R D e] (ι : Type v) : SemiHilbert (ι → X) R D e := sorry

instance : SemiInner ℝ ℝ Unit (λ r _ => r) := sorry

--------------

constant foo {X Y} : (X → Y) → (X → Y) := id
theorem  foo_apply {X Y} [Vec X] [Vec Y] (f : X → Y) [IsLin f] (x dx : X)
        : foo f x = f x := sorry

def norm {X} [Trait X] [inst : SemiInner X (Trait.R X) (Trait.D X) Trait.eval] (x : X) : Trait.R X := sorry

def sum {n} {α : Type} (f : Fin n → α) : α := sorry

set_option trace.Meta.synthInstance true in
example (x) : (foo λ (x : Fin n → ℝ) (j : Fin n) => sum λ i => norm (x i)) x = x := 
by 
  rw [foo_apply]
  admit
```

**Comment by leodemoura** [comment]
@lecopivo Thanks for posting the mwe. Not sure it is related to your original issue. The "unknown metavariable" error in the mwe is due to an invalid trace message. I pushed a fix issue for this issue, but not sure whether it also fixes the original issue.  Could you please try?

**Comment by lecopivo** [comment]
Yes the error message is correct now, both in mwe an in the original problem. 

Unfortunately, the TC still gets into an infinite loop but that is a different issue, mine not Lean's. The structure of typeclasses is inherently flawed. The problematic instance is:
```
instance (X R) [Vec R] [SemiHilbert X R] (ι : Type v) : SemiHilbert (ι → X) R := sorry
```
Ideally I would reverse the order of `[Vec R]` and `[SemiHilbert X R]`, but that is not possible as the definition of `SemiHilbert` requires `Vec R`. I would like to somehow express, do not bother synthesizing `Vec R` if there is no hope in synthesizing `SemiHilbert X R`.
